# Generated by Django 4.2 on 2023-06-09 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0011_blog_blog_meta_keyword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_meta_keyword',
            new_name='blog_meta_keywords',
        ),
    ]
