# Generated by Django 4.2 on 2023-06-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.image'),
        ),
    ]
