# Generated by Django 4.2 on 2023-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_image_description_profile_facebook_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('http_referer', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
