# Generated by Django 4.2 on 2023-07-04 12:14

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0017_alter_post_cover_image_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideProject',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', martor.models.MartorField()),
                ('meta_desc', models.CharField(blank=True, max_length=150)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
                (
                    'cover_image',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to='blog.image',
                    ),
                ),
                (
                    'project_owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='blog.profile'
                    ),
                ),
            ],
            options={
                'ordering': ['created_date'],
                'abstract': False,
            },
        ),
    ]
