# Generated by Django 4.2 on 2023-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_sideproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='path_info',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='http_referer',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='remote_addr',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
